ecohub/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("about", views.about, name="about"),
    path("register", views.register, name="register"),
    path("login", views.login_request, name="login"),
    path("logout", views.logout_request, name="logout"),
    path("messages", views.messages_view, name="messages"),
    path("messages/message/<int:message_id>", views.message_view, name="message_view"),
    path("home", views.home, name="home"),
    path("news", views.news_view, name="news"),
    path("news/<int:article_id>/article", views.article_view, name="article"),
    path("news/category/<int:category_id>", views.news_category, name="news_category"),
    path("blogs", views.blogs_view, name="blogs"),
    path("blogs/<int:blog_id>/blog", views.blog_view, name="blog"),
    path("blogs/category/<int:category_id>", views.blog_category, name="blog_category"),
    path("blogs/myblogs", views.myblogs_view, name="myblogs"),
    path("blogs/blogwriting", views.blogwriting, name="blogwriting"),
    path("projects", views.projects, name="projects"),
    path("projects/category/<int:category_id>", views.project_category, name="project_category"),
    path("projects/myprojects", views.myprojects_view, name="myprojects"),
    path("projects/start_project", views.start_project, name="start_project"),
    path("projects/<int:project_id>/project", views.project_view, name="project"),
    path("projects/<int:project_id>/support_project", views.fund_project, name="support_project"),
    path("projects/<int:project_id>/contact_owner", views.contacting, name="contact_owner")
]

final_project/urls.py
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('ecohub.urls')),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

ecohub/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User

# Create your models here.
class NewsCategory(models.Model):
    category_name = models.CharField(max_length=255)
    category_summary = models.CharField(max_length=255)

    class Meta:
        # Gives the proper plural name for admin
        verbose_name_plural = "News Categories"

    def __str__(self):
        return self.category_name

class Article(models.Model):
    news_category = models.ForeignKey(NewsCategory, default=1, verbose_name="Category", on_delete=models.SET_DEFAULT)
    article_title = models.CharField(max_length=255)
    published = models.DateTimeField('date published')
    summary = models.TextField(default="Short Abstract")
    author = models.CharField(max_length=127)
    text = models.TextField()

    def __str__(self):
        return self.article_title

class Blog(models.Model):
    category = models.ForeignKey(NewsCategory, default=1, verbose_name="Category", on_delete=models.SET_DEFAULT)
    author = models.CharField(max_length=127, default="author")
    published = models.DateField(auto_now_add=True)
    title = models.CharField(max_length=255)
    abstract = models.TextField(default='Abstract')
    content = models.TextField()

    def __str__(self):
        return self.title

class Project(models.Model):
    owner = models.ForeignKey(User, default=1, on_delete=models.SET_DEFAULT)
    category = models.ForeignKey(NewsCategory, default=1, verbose_name="Category", on_delete=models.SET_DEFAULT)
    title = models.CharField(max_length=255)
    published = models.DateField(auto_now_add=True)
    abstract = models.TextField()
    description = models.TextField()
    target_funds = models.BigIntegerField()
    current_funds = models.BigIntegerField(default=0)
    attachment = models.FileField(upload_to='uploads/%Y/%m/%d/', blank=True)    

    def __str__(self):
        return f"{self.title}"

class Message(models.Model):
    SUBJECTS = (
        ('more', 'More information'),
        ('collaboration', 'Collaboration offer'),
        ('join', 'Join Project'),
        ('invest', 'Make investment'),
        ('advertise', 'Advertisement'),
        ('other', 'Other business offer'),
    )
    project_reference = models.ForeignKey(Project, default=1, verbose_name="Project", on_delete=models.SET_DEFAULT)
    sender = models.ForeignKey(User, default=1, on_delete=models.SET_DEFAULT)
    sent = models.DateTimeField('date sent', default=datetime.now())
    subject = models.CharField(max_length=64, choices=SUBJECTS)
    message_text = models.TextField()
    read = models.BooleanField(default=False)

class Fund(models.Model):
    project_reference = models.ForeignKey(Project, default=1, verbose_name="Project", on_delete=models.SET_DEFAULT)
    donated = models.DateTimeField('date sent', default=datetime.now())
    contributor = models.ForeignKey(User, default=1, on_delete=models.SET_DEFAULT)
    amount = models.BigIntegerField()

    def __str__(self):
        return f"${self.amount} from {self.contributor} for {self.project_reference}"

ecohub/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from datetime import datetime
from tinymce import TinyMCE, HTMLField
from tinymce.widgets import TinyMCE
from creditcards.forms import CardNumberField, CardExpiryField, SecurityCodeField

from .models import NewsCategory

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    email = forms.EmailField(max_length=150)


    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name',
                    'email', 'password1', 'password2',)


class BlogForm(forms.Form):
    category = forms.ModelChoiceField(queryset=NewsCategory.objects.all(), empty_label="--Select Category--")
    title = forms.CharField(max_length=255)
    abstract = forms.CharField(widget=TinyMCE(mce_attrs={'height': 150}))
    content = forms.CharField(widget=TinyMCE(mce_attrs={'height': 500}))

class ProjectForm(forms.Form):
    category = forms.ModelChoiceField(queryset=NewsCategory.objects.all(), empty_label="--Select Category--")
    title = forms.CharField(max_length=255)
    abstract = forms.CharField(widget=TinyMCE(mce_attrs={'height': 150}))
    description = forms.CharField(widget=TinyMCE(mce_attrs={'height': 500}))
    target_funds = forms.IntegerField()
    attachment = forms.FileField(required=False)

class ContactForm(forms.Form):
    SUBJECTS = (
        ('more', 'More information'),
        ('collaboration', 'Collaboration offer'),
        ('join', 'Join Project'),
        ('invest', 'Make investment'),
        ('advertise', 'Advertisement'),
        ('other', 'Other business offer'),
    )
    subject = forms.ChoiceField(choices=SUBJECTS)
    message = forms.Textarea()

ecohub/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages

from datetime import datetime

from .forms import SignUpForm, BlogForm, ContactForm, ProjectForm
from .models import NewsCategory, Article, Blog, Project, Message, Fund

import stripe
# Set stripe API key
stripe.api_key = 'sk_test_VGoMuLdyerBy0LFHj08fYpR200kOwbK9uY'


# Create your views here.
def index(request):
    return render(request, 'ecohub/index.html', context={'welcome': "Welcome to EcoHub!"})

def about(request):
    return render(request, 'ecohub/about.html')

# AUTHENTICATION 

def register(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect(home)
        else:
            print("invalid form")

    form = SignUpForm
    return render(request, 'ecohub/register.html', context={"form": form})

def login_request(request):
    # If login form is posted log user in
    if request.method == "POST":
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect(home)
            else:
                messages.info(request, f"Login failed")
    
    # Else render index page            
    form = AuthenticationForm
    return render(request, 'ecohub/login.html', {"form": form})

def logout_request(request):
    logout(request)
    return redirect(index)

def home(request):
    context = {
        "message": "You have succesfully authenticated"
    }
    return render(request, 'ecohub/home.html', context)

# NEWS SECTION

def news_view(request):
    context = {
        "news": Article.objects.all(),
        "categories": NewsCategory.objects.all(),
    }    
    return render(request, 'ecohub/news.html', context=context)

def news_category(request, category_id):
    try:
        news = Article.objects.filter(news_category=category_id)  
    except Article.DoesNotExist:
        news = None
    context = {
            "news": news,
            "categories": NewsCategory.objects.all(),
    }    
    return render(request, 'ecohub/news.html', context=context)


def article_view(request, article_id):
    article = Article.objects.get(pk=article_id)
    context = {
        "article": article,
        "categories": NewsCategory.objects.all(),
    }
    return render(request, 'ecohub/article.html', context=context)

# BLOGS SECTION

def blogs_view(request):
    context = {
        "blogs": Blog.objects.all(),
        "categories": NewsCategory.objects.all()
    }    
    return render(request, 'ecohub/blogs.html', context=context)

def blog_view(request, blog_id):
    blog = Blog.objects.get(pk=blog_id)
    context = {
        "blog": blog,
        "categories": NewsCategory.objects.all(),
    }
    return render(request, 'ecohub/blog.html', context=context)

def blog_category(request, category_id):
    try:
        blogs = Blog.objects.filter(category=category_id)     
    except Blog.DoesNotExist:
        blogs = None
    context = {
        "blogs": blogs,
        "categories": NewsCategory.objects.all(),
    }
    return render(request, 'ecohub/blogs.html', context=context)

def myblogs_view(request):
    author = request.user.first_name + " " + request.user.last_name
    #print(author)
    try:
        blogs = Blog.objects.filter(author=author)
    except Blog.DoesNotExist:
        context = {"blogs": None}
    context = {
        "blogs": blogs,
        "categories": NewsCategory.objects.all()
    }
    return render(request, 'ecohub/blogs.html', context=context)

def blogwriting(request):
    if request.method == "POST":
        form = BlogForm(request.POST)
        if form.is_valid():
            # Create new blog in the database
            # Get the form data
            category = form.cleaned_data["category"]
            title = form.cleaned_data["title"]
            abstract = form.cleaned_data["abstract"]
            content = form.cleaned_data["content"]
            
            # Compile the name of the user as author
            author = request.user.first_name + " " + request.user.last_name

            # Create new Blog object and save
            new_blog = Blog(category=category, author=author, title=title, abstract=abstract, content=content)
            new_blog.save()

            # redirect to my blogs
            return redirect(myblogs_view)
    else:    
        form = BlogForm()
        return render(request, 'ecohub/blogwriting.html', context= {"form": form, "categories": NewsCategory.objects.all()})

# PROJECT SECTION

def projects(request):
    # get all projects
    context = {
        "projects": Project.objects.all(),
        "categories": NewsCategory.objects.all()
    }
    return render(request, 'ecohub/projects.html', context=context)

def project_categories(request):
    categories = NewsCategory.objects.all()
    context = {
        "categories": categories,
    }
    return render(request, 'ecohub/projectcategories.html', context=context)

def project_category(request, category_id):
    try:
        projects = Project.objects.filter(category=category_id)     
    except Project.DoesNotExist:
        projects = None
    context = {
        "projects": projects,
        "categories": NewsCategory.objects.all()
    }
    return render(request, 'ecohub/projects.html', context=context)

def myprojects_view(request):
    owner = request.user.first_name + " " + request.user.last_name
    try:
        projects = Project.objects.filter(owner=request.user)
    except Project.DoesNotExist:
        context = {"project": None}
    context = {
        "projects": projects,
        "categories": NewsCategory.objects.all()
    }
    return render(request, 'ecohub/projects.html', context=context)

def start_project(request):
    if request.method == "POST":
        form = ProjectForm(request.POST, request.FILES)
        if form.is_valid():
            # Get form data
            category = form.cleaned_data["category"]
            title = form.cleaned_data["title"]
            abstract = form.cleaned_data["abstract"]
            description = form.cleaned_data["description"]
            target_funds = form.cleaned_data["target_funds"]
            # Check wether attachemnet was uploaded
            if request.FILES:
                # Create new Project object with attachement
                new_project = Project(owner=request.user, category=category, title=title, abstract=abstract, description=description, target_funds=target_funds, attachment=request.FILES['attachment'])
            else:
                # Create new project without attachement
                new_project = Project(owner=request.user, category=category, title=title, abstract=abstract, description=description, target_funds=target_funds)
            # Save new project
            new_project.save()
            # Redirect user to myproject page
            return redirect(myprojects_view)
        else:
            form = ProjectForm()
            context = {
                "form": form,
                "categories": NewsCategory.objects.all(),
                "error": "Invalid form"
            }
        return render(request, 'ecohub/startproject.html', context=context)
    else:
        form = ProjectForm()
        context = {
            "form": form,
            "categories": NewsCategory.objects.all()
        }
        return render(request, 'ecohub/startproject.html', context=context)

def project_view(request, project_id):
    project = Project.objects.get(pk=project_id)
    if project.owner == request.user:
        contributions = Fund.objects.filter(project_reference=project)
    else:
        contributions = False
    context = {
        "project": project,
        "categories": NewsCategory.objects.all(),
        "contributions": contributions
    }
    return render(request, 'ecohub/project.html', context=context)

def fund_project(request, project_id):
    project = Project.objects.get(pk=project_id)
    if request.method == "POST":
        amount = request.POST["amount"]
        print(f"Received funds: {amount}")
        project.current_funds += int(amount)
        project.save()
        new_fund = Fund(project_reference=project, contributor=request.user, amount=int(amount))
        new_fund.save()
        # Define stripe Payment Intent
        intent = stripe.PaymentIntent.create(
            amount=100,
            currency='usd',
            # Verify your integration in this guide by including this parameter
            metadata={'integration_check': 'accept_a_payment'},
        )
        return redirect(project_view, project_id)
    else:
        # Define context for page rendering
        context = {
            'project': project
        }
        return render(request, 'ecohub/fundproject.html', context=context)


def contacting(request, project_id):
    project = Project.objects.get(pk=project_id)
    if request.method == "POST":
        subject = request.POST["subject"]
        message = request.POST["message"]
        # Create Message object and save to the database
        new_message = Message(project_reference=project, sender=request.user, subject=subject, message_text=message)
        new_message.save()
        print(f"{new_message} message sent")
        return render(request, 'ecohub/contactpage.html', context={"sent": True, "project": project})
    else:
        form = ContactForm()
        #Define context for page rendering
        context = {
            'sent': False,

ecohub/templates/ecohub/about.html
{% extends "ecohub/base.html" %}

{% block title %}
About EcoHub
{% endblock %}

{% block body %}
    <div class="jumbotron">
        <h1 class="display-4">Hello and Welcome to EcoHub!</h1>
        <p class="lead">A hub of ecological technologies</p>
        <hr class="my-4">
        <section>
            <p>At ecohub you can find all the latest news about ecological and enviroment friendly technologies. From the technologies of the past to
                to the latest inventions. From growing Startups to biggest Corporation. From wisdom of our ancestors to wildest futuristic ideas.
                You can find anything in one EcoHub.
            </p>
        </section>
        
        <section>
            <p>
                In our Blog section you can find the ideas and opinions of bloggers from all around the world. Are you looking for an inspiration 
                or food for tought? EcoHub is the place. Do you want to become a blogger? Every user can write his own blogs. You are free to express
                your ideas at our platform. EcoHub is the place to share ideas and build the future.
            </p>
        </section>
        
        <section>
            <p>
                Do you have a Startup or project which needs funding? EcoHub gives you a platform where you can present your project and request a funding.
                From crowdfunding to big business investment or just colaboration and help from other tech people you can get all the funding and resources
                you need. EcoHub helps you to bring your idea into reality and build the future.
            </p>
        </section>
        
        <p>
            <a class="btn btn-primary btn-lg" href="{% url 'register' %}" role="button">Join EcoHub</a>
        </p>        
    </div>    
{% endblock %}

ecohub/templates/ecohub/article.html
{% extends "ecohub/base.html" %}

{% block title %}
EcoHub - {{ article.title }}
{% endblock %}

{% block body %}
    {% include 'ecohub/includes/newsnav.html' %} 
    <div class="card article-card">
        <div class="card-body">
            <h5 class="card-title">{{ article.article_title }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">{{ article.published }}</h6>
            <p class="card-text">{{ article.text|safe }}</p>
            <hr>
            <h6 class="card-subtitle mb-2 text-muted">{{ article.author }}</h6>
        </div>                    
    </div>
{% endblock %}

ecohub/templates/ecohub/blog.html
{% extends "ecohub/base.html" %}

{% block title %}
EcoHub - {{ blog.title }}
{% endblock %}

{% block body %}
    {% include 'ecohub/includes/blognav.html' %}
    <div class="card blog" style="width: 80%;">
        <div class="card-body">
            <h5 class="card-title">{{ blog.title }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">{{ blog.published }}</h6>
            <p class="card-text">{{ blog.abstract|safe }}</p>
            <hr>
            <p class="card-text">{{ blog.content|safe }}</p>
            <hr>
            <h6 class="card-subtitle mb-2 text-muted">{{ blog.author }}</h6>
        </div>                    
    </div>
{% endblock %}

ecohub/templates/ecohub/blogwriting.html
{% extends "ecohub/base.html" %}

{% block title %}
EcoHub - Write a blog
{% endblock %}

{% block media %}
    {{ form.media }}
{% endblock %}

{% block body %}
    {% include 'ecohub/includes/blognav.html' %}
    <div class="card card-body writingCard">
        <form method="POST" class="blogForm">
            {% csrf_token %}
            {{ form.media }}
            <div class="form-group">
                <h3>Title:</h3>
                {{ form.title }}
            </div>
            <div class="form-group">
                <h3>Category:</h3>
                {{ form.category }}
            </div>
            <!--
            <div class="form-group">
                <h3>Date:</h3>
                {{ form.date }}
            </div>
            -->            
            <div class="form-group">
                <h3>Abstract:</h3>
                {{ form.abstract }}
            </div>
            <div class="form-group">
                <h3>Blog text:</h3>
                {{ form.content }}
            </div>
            <p>
                <button type="submit" class="btn btn-primary">Post blog</button>
            </p>   
        </form>
    </div>    
{% endblock %}

ecohub/templates/ecohub/contactpage.html
{% extends "ecohub/base.html" %}

{% block title %}
EcoHub - Project Categories
{% endblock %}

{% block body %}
    {% include 'ecohub/includes/projectnav.html' %}

    {% if sent %}
        <p>
            Your message was sent
        </p>
        <p>
            <a href="{% url 'project' project.id %}" class="btn btn-primary">Go To Projects</a>
        </p>
    {% else %}
        <div class="project-card">
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                        <label for="subject" style="font-size: large;">Select subject</label>
                        <select class="form-control" id="subject" name="subject">
                            <option value="more">More information</option>
                            <option value="collaboration">Collaboration offer</option>
                            <option value="join">Join project</option>
                            <option value="invest">Make investment</option>
                            <option value="advertise">Advertisement</option>
                            <option value="other">Other business offer</option>
                        </select>
                </div>
                <div class="form-group">
                    <label for="privateMessage" style="font-size: large;">Type your message here</label>
                    <textarea class="form-control" id="privateMessage" rows="5" name="message" placeholder="Your message"></textarea>
                </div>
                <p>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </p>
            </form>
        </div>
    {% endif %}
{% endblock %}

ecohub/templates/ecohub/login.html
{% extends "ecohub/base.html" %}

{% block title %}
Login
{% endblock %}

{% block body %}
    <section class="login">
        <div class="card card-body">
            <form method="POST" id="loginForm">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_userName">Username</label>
                    {{ form.username }}
                    <p>{{ form.username.error }}</p>
                </div>
                    
                <div class="form-group">
                    <label for="id_password">Password</label>
                    {{ form.password }}
                    <p>{{ form.password.error }}</p>
                </div>
                
                <p>
                    <button type="submit" class="btn btn-primary">Log In</button>
                </p>                        
            </form>
        </div>    
    </section>    
{% endblock %}

ecohub/templates/ecohub/message.html
{% extends "ecohub/base.html" %}

{% block title %}
    EcoHub - {{ message.message_subject }} - {{ message.project_reference }}
{% endblock %}

{% block body %}
    <div class="card blog" style="width: 80%;">
        <div class="card-body">
            <header>
                <p>
                    <strong>From: </strong>{{ message.sender.first_name }} {{ message.sender.last_name }}; email: {{ message.sender.email }}
                </p>
                <p>
                   <strong>Project: </strong>{{ message.project_reference }}
                </p>
                <p>
                    <strong>Subject: </strong>{{ message.get_subject_display }}
                </p>            
                <p>
                    <strong>Date: </strong>{{ message.sent }}
                </p>                
            </header>            
            <hr>
            <article>
                <p>
                    {{ message.message_text }}
                </p>
            </article>        
        </div>
    </div>
{% endblock %}

ecohub/templates/ecohub/messages.html
{% extends "ecohub/base.html" %}

{% block title %}
    EcoHub - Messages
{% endblock %}

{% block body %}
    <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item">
        <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Inbox</a>
        </li>
        <li class="nav-item">
        <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Sent</a>
        </li>
    </ul>
    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
            <p>
                <h2>Received messages:</h2>
                <section class="messages" id="in_messages">
                    <div class="list-group">
                        <a href="#" class="list-group-item list-group-item-action active">
                          Date-From-Project-Subject
                        </a>
                        {% if in_messages %}
                            {% for m in in_messages %}
                                <a href="{% url 'message_view' m.id %}" class="list-group-item list-group-item-action">{{ m.sent }} - {{ m.sender.first_name }} {{ m.sender.last_name }} - {{ m.project_reference }} - {{ m.get_subject_display }}</a>
                            {% endfor %}
                        {% else %}
                            <p><h3>You have no messages.</h3></p>
                        {% endif %}
                    </div>
                </section>
            </p>
        </div>
        <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
            <p>
                <h2>Sent messages:</h2>
                <section class="messages" id="sent_messages">
                    <section class="messages" id="in_messages">
                        <div class="list-group">
                            <a href="#" class="list-group-item list-group-item-action active">
                              Date-From-Project-Subject
                            </a>
                            {% if sent_messages %}
                                {% for m in sent_messages %}
                                    <a href="{% url 'message_view' m.id %}" class="list-group-item list-group-item-action">{{ m.sent }} - {{ m.sender.first_name }} {{ m.sender.last_name }} - {{ m.project_reference }} - {{ m.get_subject_display }}</a>
                                {% endfor %}
                            {% else %}
                                <p><h3>You have no messages.</h3></p>
                            {% endif %} 
                        </div>
                    </section>
                </section>
            </p>
        </div>
    </div>    
{% endblock %}

ecohub/templates/ecohub/news.html
{% extends "ecohub/base.html" %}

{% block title %}
EcoHub - News
{% endblock %}

{% block body %}
    {% include 'ecohub/includes/newsnav.html' %}
    {% if not news %}
        <p>Sorry, There are no news in this category.</p>
    {% else %}
        <div class="container">
            {% for article in news %}
                <div class="row">
                    <div class="col">
                        <div class="card" style="width: 100%;">
                            <div class="card-body">
                                <h5 class="card-title">{{ article.article_title }}</h5>
                                <h6 class="card-subtitle mb-2 text-muted">{{ article.published }}</h6>
                                <p class="card-text">{{ article.summary|safe }}</p>
                                <a href="{% url 'article' article.id %}" class="card-link">Full article</a>                    
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}        
        </div>
    {% endif %}
{% endblock %}

ecohub/templates/ecohub/register.html
{% extends "ecohub/base.html" %}

{% block title %}
SignUp
{% endblock %}

{% block body %}   
    <main>
        <section class="register">            
            <div class="card card-body">
                <form method="POST" class="regForm">
                    {% csrf_token %}
                    <div class="form-group">
                        <p>
                            <label for="id_username">Username</label>
                            {{ form.username }}      
                        </p>                                          
                    </div>
                    
                    <div class="form-group">
                        <p>
                            <label for="id_first_name">First name</label>
                            {{ form.first_name }}  
                        </p>                                        
                    </div>
                    
                    <div class="form-group">
                        <p>
                            <label for="id_last_name">Last name</label>
                            {{ form.last_name }}
                        </p>
                    </div>
                    
                    <div class="form-group">
                        <p>
                            <label for="id_email">Email</label>
                            {{ form.email }}
                            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                        </p>                      
                    </div>
                   
                    <div class="form-group">
                        <p>
                            <label for="id_password1">Password</label>
                            {{ form.password1 }}
                        </p>                                            
                    </div>
                    
                    <div class="form-group">
                        <p>
                            <label for="password2">Confirm your Password</label>
                            {{ form.password2 }}
                        </p>                                                
                    </div>                    
                    <button type="submit" class="btn btn-primary">Register</button>
                </form>
            </div>
        </section>   
    </main>
{% endblock %}